server:
  port: 8888
spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/bilgejava6/java5cloudconfig.git"
          default-label: main
          skip-ssl-validation: true
          username: bilgejava6
          password: ${GIT_PASSWORD}
# DİKKATTTTTT
# BURADA PASSWORD asla ve asla tutulmamalıdır. bunun yerine env kullanılarak çekilmelidir.
# diğer türlü bu bilgiyi GIT e push ladığınız zaman ya bu token silinecektir. yada hesabınız
# güvenlik açısından askıya alınacaktır.
