server:
  port: 80
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - RewritePath= /(?<segment>.*), /api/v1/$\{segment}
      routes:
        # id tanımlanacak yönlendirme işlemini adı dır, burada gateway e gelen isteğin
        # yakalanarak iletilmesi gereken adrese iletilmesi işlemi yapılır.
        # http://localhost/auth/******  -> http://localhost:9090/auth/*****
#        http://localhost/auth/message -> http://localhost:9090/api/v1/message
        - id: auth-micro-service
          predicates:
            - Path=/auth/**
          uri: http://localhost:9090
        - id: user-micro-service
          predicates:
            - Path=/user/**
          uri: http://localhost:9093
