server:
  port: 9093


spring:
  logging:
    root: DEBUG
    file:
      name: userservice.log
  security:
    user:
      name: muhammet
      password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-micro-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://35.222.86.204:5432/UserDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

redis:
  host: "localhost"
  port: 6379
