server:
  port: 9093


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/UserDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update